---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandacloud-app
  labels:
    app: pandacloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pandacloud-app
  template:
    metadata:
      labels:
        app: pandacloud-app
    spec:
      containers:
      - name: pandacloud-container
        image: 712062877401.dkr.ecr.us-east-1.amazonaws.com/tic-tac-toe:latest
        ports:
        - containerPort: 3000
...